name: Build APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: kivy/buildozer:latest
      options: --workdir /github/workspace

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Show root files (debug)
        run: ls -la

      - name: Show recursive (debug)
        run: ls -R .

      - name: Build APK
        run: |
          yes|buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: MyApp-APK
          path: .buildozer/android/platform/build/dists/*/bin/myapp.apk
