name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: kivy/buildozer:latest  # 使用官方 Docker，已含 Android SDK/NDK/Ant

    steps:
      - uses: actions/checkout@v4

      - name: Show Python version
        run: python --version

      - name: Build APK
        run: |
          yes|buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: MyApp-APK
          path: .Myapp/bin/MyApp.apk  # buildozer 生成的 APK 位置
